// One-off generator: bundles src/ocr-worker-entry.cjs (+ its tesseract.js /
// tesseract.js-core dependency graph) into a single self-contained script,
// and embeds that bundle plus the matching WASM core and English trained
// data as base64 constants in src/ocr-assets.js.
//
// Re-run after upgrading tesseract.js / tesseract.js-core, or after editing
// ocr-worker-entry.cjs:
//   node gen_ocr_assets.mjs
import { build } from 'esbuild';
import fs from 'node:fs';

const NODE_BUILTINS = [
  'fs', 'path', 'zlib', 'worker_threads', 'crypto', 'stream', 'buffer',
  'util', 'os', 'http', 'https', 'url', 'events', 'assert', 'child_process',
  'net', 'tls', 'perf_hooks',
];

const result = await build({
  entryPoints: ['src/ocr-worker-entry.cjs'],
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node18',
  write: false,
  external: NODE_BUILTINS,
  logLevel: 'warning',
});

const bundleText = result.outputFiles[0].text;
const wasmBuffer = fs.readFileSync(
  'node_modules/tesseract.js-core/tesseract-core-lstm.wasm'
);
const tessdataBuffer = fs.readFileSync('src/tessdata/eng.traineddata.gz');

const out = `// Auto-generated by gen_ocr_assets.mjs — do not hand-edit.
// Embeds three assets as base64 so they're guaranteed part of the static
// import graph Forge's bundler follows (no runtime filesystem path lookup
// needed to locate them): the esbuild-bundled OCR worker script, the
// matching WASM OCR core, and the English trained data. See the note at the
// top of ocr-worker-entry.cjs for why this exists.

export const OCR_WORKER_BUNDLE_BASE64 =
  '${Buffer.from(bundleText, 'utf-8').toString('base64')}';

export const OCR_CORE_WASM_BASE64 =
  '${wasmBuffer.toString('base64')}';

export const ENG_TRAINEDDATA_GZ_BASE64 =
  '${tessdataBuffer.toString('base64')}';
`;

fs.writeFileSync('src/ocr-assets.js', out);
console.log(
  `Wrote src/ocr-assets.js — bundle ${(bundleText.length / 1024).toFixed(1)}KB, ` +
    `wasm ${(wasmBuffer.length / 1024 / 1024).toFixed(2)}MB, ` +
    `tessdata ${(tessdataBuffer.length / 1024 / 1024).toFixed(2)}MB (all base64-inflated ~33%)`
);
