import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import api, { route } from '@forge/api';
// Import pdf-parse's inner module directly, not the package entrypoint.
// The entrypoint runs a debug self-test guarded by `!module.parent`, which
// is true under Forge's bundler and throws trying to read a test fixture
// that isn't part of the bundle.
import pdfParse from 'pdf-parse/lib/pdf-parse.js';
import mammoth from 'mammoth';
import ExcelJS from 'exceljs';
import { createWorker } from 'tesseract.js';
import {
  OCR_WORKER_BUNDLE_BASE64,
  OCR_CORE_WASM_BASE64,
  ENG_TRAINEDDATA_GZ_BASE64,
} from './ocr-assets.js';

// NOTE ON tesseract.js IN FORGE — this took two failed deploys to nail down:
// tesseract.js's Node build spawns its recognizer on a worker_threads.Worker
// pointed at a separate file, and its WASM core loader needs a sibling
// .wasm file — both located via `__dirname`-based path computation *inside
// their own modules*. That fails in Forge: not just tesseract.js's own
// internal `__dirname` (confirmed — its computed workerPath came out as a
// bare relative string, and worker_threads rejected it), but *our own*
// import.meta.url-based `__dirname` too (confirmed on retry — same failure
// shape, this time from our path). Forge's bundler evidently doesn't
// preserve a real filesystem location for any module's self-reference, only
// its own function entry.
//
// Fix: never compute a path to an existing file at all. src/ocr-assets.js
// (generated by gen_ocr_assets.mjs) embeds three things as base64 JS
// constants — an esbuild bundle of a custom worker entry (see
// ocr-worker-entry.cjs) containing tesseract.js's worker-script logic *and*
// one fixed WASM core variant inlined together, the matching .wasm binary,
// and the English trained data. Being literal source, they're guaranteed
// part of the static import graph Forge's bundler follows correctly. At
// call time we decode and write all three to os.tmpdir() — always a real,
// writable, absolute path in a Lambda-style sandbox, no computation needed
// — then point tesseract.js at those hardcoded paths. Once the worker
// bundle is running as a genuine standalone file on a real path, its own
// __dirname is correct again, which is what lets the inlined WASM loader
// (which also does its own __dirname-relative lookup) find its .wasm file.
const OCR_TMP_DIR = os.tmpdir();
const OCR_WORKER_TMP_PATH = path.join(OCR_TMP_DIR, 'ocr-worker-bundle.cjs');
const OCR_WASM_TMP_PATH = path.join(OCR_TMP_DIR, 'tesseract-core-lstm.wasm');
const OCR_TRAINEDDATA_TMP_PATH = path.join(OCR_TMP_DIR, 'eng.traineddata.gz');

let ocrAssetsWritten = false;
function ensureOcrAssetsOnDisk() {
  if (ocrAssetsWritten) return;
  fs.writeFileSync(OCR_WORKER_TMP_PATH, OCR_WORKER_BUNDLE_BASE64, 'base64');
  fs.writeFileSync(OCR_WASM_TMP_PATH, OCR_CORE_WASM_BASE64, 'base64');
  fs.writeFileSync(OCR_TRAINEDDATA_TMP_PATH, ENG_TRAINEDDATA_GZ_BASE64, 'base64');
  ocrAssetsWritten = true;
}

const MAX_ATTACHMENT_BYTES = 5 * 1024 * 1024; // 5MB
// OCR is much slower than the other parsers and Forge functions have a hard
// ~25s execution timeout, so images get a smaller cap to keep recognition
// time (plus cold-start engine load) comfortably inside that budget.
const MAX_IMAGE_BYTES = 3 * 1024 * 1024; // 3MB
const MAX_TEXT_CHARS = 20000;

const SUPPORTED_PARSERS = {
  'application/pdf': parsePdf,
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': parseDocx,
  'text/plain': parseText,
  'text/markdown': parseText,
  'text/x-markdown': parseText,
  'text/csv': parseText,
  'application/json': parseText,
  'image/png': parseImage,
  'image/jpeg': parseImage,
  // Modern .xlsx only. Legacy binary .xls (application/vnd.ms-excel) isn't
  // supported — exceljs doesn't read that format.
  //
  // Deliberately using exceljs here instead of the more commonly reached-for
  // "xlsx" (SheetJS) package: the last version SheetJS published to npm,
  // 0.18.5, has two unpatched high-severity advisories (prototype pollution
  // GHSA-4r6h-8v6p-xvw6 and ReDoS GHSA-5pgg-2g8v-p4x9) that are directly
  // triggerable by a crafted file — exactly the input this handler feeds it,
  // since every spreadsheet here comes from a Jira attachment any issue
  // watcher could have uploaded. SheetJS's fix only ships from their own CDN,
  // not npm. exceljs has no vulnerability in its own parsing path.
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
    parseExcel,
};

export async function handler(payload) {
  const { issueIdOrKey, attachmentId } = payload ?? {};

  if (!issueIdOrKey) {
    return { success: false, error: 'issueIdOrKey is required.' };
  }

  let attachments;
  try {
    attachments = await getIssueAttachments(issueIdOrKey);
  } catch (err) {
    return { success: false, error: err.message };
  }

  const targets = attachmentId
    ? attachments.filter((a) => String(a.id) === String(attachmentId))
    : attachments;

  if (attachmentId && targets.length === 0) {
    return {
      success: false,
      error: `Attachment ${attachmentId} not found on issue ${issueIdOrKey}.`,
    };
  }

  const results = await Promise.all(targets.map(readAttachment));

  return {
    success: true,
    issueIdOrKey,
    attachmentCount: attachments.length,
    attachments: results,
  };
}

async function getIssueAttachments(issueIdOrKey) {
  const res = await api
    .asApp()
    .requestJira(route`/rest/api/3/issue/${issueIdOrKey}?fields=attachment`);

  if (!res.ok) {
    const body = await res.text();
    throw new Error(
      `Failed to load issue ${issueIdOrKey}: ${res.status} ${body}`
    );
  }

  const { fields } = await res.json();
  return fields?.attachment ?? [];
}

async function readAttachment(attachment) {
  const { id, filename, mimeType, size } = attachment;
  const base = { id, filename, mimeType, size };

  const parser = SUPPORTED_PARSERS[mimeType];
  if (!parser) {
    return {
      ...base,
      supported: false,
      reason: `Unsupported attachment type: ${mimeType}`,
    };
  }

  const maxBytes = mimeType.startsWith('image/')
    ? MAX_IMAGE_BYTES
    : MAX_ATTACHMENT_BYTES;
  if (size > maxBytes) {
    return {
      ...base,
      supported: true,
      error: `Attachment exceeds ${
        maxBytes / (1024 * 1024)
      }MB limit (${(size / (1024 * 1024)).toFixed(1)}MB) and was skipped.`,
    };
  }

  try {
    const buffer = await downloadAttachmentContent(id);
    let text = await parser(buffer);
    const truncated = text.length > MAX_TEXT_CHARS;
    if (truncated) text = text.slice(0, MAX_TEXT_CHARS);
    return { ...base, supported: true, text, truncated };
  } catch (err) {
    return {
      ...base,
      supported: true,
      error: `Failed to extract content: ${err.message}`,
    };
  }
}

async function downloadAttachmentContent(attachmentId) {
  const res = await api
    .asApp()
    .requestJira(route`/rest/api/3/attachment/content/${attachmentId}`);

  if (!res.ok) {
    throw new Error(`Download failed with status ${res.status}`);
  }

  const arrayBuffer = await res.arrayBuffer();
  return Buffer.from(arrayBuffer);
}

async function parseText(buffer) {
  return buffer.toString('utf-8');
}

async function parsePdf(buffer) {
  const data = await pdfParse(buffer);
  const text = (data.text ?? '').trim();
  if (!text) {
    // pdf-parse only reads a PDF's embedded text layer. A PDF with no text
    // layer at all (e.g. every page is a scanned image) parses "successfully"
    // but yields nothing — that's not a parse failure, it's a different kind
    // of file. Say so explicitly rather than returning an empty string,
    // which otherwise reads to the agent (and the user) as a silent bug.
    throw new Error(
      `No embedded text found across ${data.numpages ?? 'its'} page(s) — this ` +
        'PDF is likely scanned/image-based with no text layer. OCR for ' +
        'scanned PDF pages is not currently supported (only PNG/JPEG image ' +
        'attachments get OCR).'
    );
  }
  return text;
}

async function parseDocx(buffer) {
  const { value } = await mammoth.extractRawText({ buffer });
  return value;
}

function excelCellToText(value) {
  if (value == null) return '';
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'object') {
    if (Array.isArray(value.richText)) {
      return value.richText.map((run) => run.text).join('');
    }
    // Formula cell: prefer the cached result; fall back to the formula
    // itself if the workbook was saved without one.
    if ('result' in value) return excelCellToText(value.result);
    if ('formula' in value) return `=${value.formula}`;
    if ('text' in value) return String(value.text); // hyperlink
    if ('error' in value) return `#ERROR(${value.error})`;
  }
  return String(value);
}

async function parseExcel(buffer) {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);

  const sheetTexts = [];
  workbook.eachSheet((worksheet) => {
    const rows = [];
    worksheet.eachRow({ includeEmpty: false }, (row) => {
      const cells = [];
      row.eachCell({ includeEmpty: true }, (cell) => {
        cells.push(excelCellToText(cell.value));
      });
      rows.push(cells.join('\t'));
    });
    sheetTexts.push(`# Sheet: ${worksheet.name}\n${rows.join('\n')}`);
  });

  const text = sheetTexts.join('\n\n').trim();
  if (!text) {
    throw new Error('No readable content found in the spreadsheet.');
  }
  return text;
}

// Reused across attachments (and, on a warm Forge invocation, across
// requests) so multiple images in one call don't each pay engine load cost.
let ocrWorkerPromise;
function getOcrWorker() {
  if (!ocrWorkerPromise) {
    ensureOcrAssetsOnDisk();
    ocrWorkerPromise = createWorker('eng', 1, {
      // 'eng' as a plain string (not a {code, data} lang object) is
      // deliberate: tesseract.js's own initialize() handler has a bug where
      // object-form langs get their raw .data bytes joined into the string
      // passed to Tesseract's Init() instead of the .code — confirmed by
      // testing it directly, it fails with "Error opening data file" and a
      // garbled path made of byte values. A plain string avoids that bug.
      langPath: OCR_TMP_DIR,
      gzip: true,
      cacheMethod: 'none', // read the materialized traineddata directly, no cache r/w
      workerPath: OCR_WORKER_TMP_PATH, // our own bundle — see note above
    }).catch((err) => {
      // Let the next call retry instead of permanently caching a failed init.
      ocrWorkerPromise = undefined;
      throw err;
    });
  }
  return ocrWorkerPromise;
}

async function parseImage(buffer) {
  const worker = await getOcrWorker();
  const {
    data: { text },
  } = await worker.recognize(buffer);
  const trimmed = (text ?? '').trim();
  if (!trimmed) {
    throw new Error('No readable text was detected in the image.');
  }
  return trimmed;
}
